omit_containers: []
instrumentation_opt_in: true
internet_detection_timeout_ms: 3000
host_webserver_port: "8080"
host_https_port: "8443"
last_started_version: v1.24.10
letsencrypt_email: ""
mkcert_caroot: ""
no_bind_mounts: false
performance_mode: none
project_tld: ddev.site
router_bind_all_interfaces: false
router_http_port: "80"
router_https_port: "443"
mailpit_http_port: "8025"
mailpit_https_port: "8026"
simple_formatting: false
table_style: default
traefik_monitor_port: "10999"
use_hardened_images: false
use_letsencrypt: false
wsl2_no_windows_hosts_mgt: false
web_environment: []
xdebug_ide_location: ""